### ISSUE TITLE
Tests fails in django 1.10

### ISSUE THREAD

**Issue by ad-m** [bameda/djmail#33]
Hello,

During #32 pull requests I identified uncompatibility with django 1.10 with following erros:
```pytb
======================================================================
ERROR: test_simple_send_email_with_magic_builder_1 (djmail.tests.SerializationEmailTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 79, in _render_message_subject
    subject = loader.render_to_string(template_name, context)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: emails/test_email2-subject.html
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/test/utils.py", line 208, in inner
    return func(*args, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/tests.py", line 275, in test_simple_send_email_with_magic_builder_1
    email = mails.test_email2('to@example.com', {'name': 'foo'})
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 159, in _dynamic_email_generator
    email_instance = template_email.make_email_object(to, context, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 90, in make_email_object
    subject = self._render_message_subject(context)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 81, in _render_message_subject
    raise exc.TemplateNotFound("Template '{0}' does not exists.".format(e))
djmail.exceptions.TemplateNotFound: Template 'emails/test_email2-subject.html' does not exists.
======================================================================
ERROR: test_proper_handlign_different_uses_cases (djmail.tests.TestTemplateEmailSending)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 79, in _render_message_subject
    subject = loader.render_to_string(template_name, context)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: emails/test_email1-subject.html
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/ad-m/djmail/djmail/tests.py", line 212, in test_proper_handlign_different_uses_cases
    context={'name': 'foo'})
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 173, in make_email
    return instance.make_email_object(to, context, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 90, in make_email_object
    subject = self._render_message_subject(context)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 81, in _render_message_subject
    raise exc.TemplateNotFound("Template '{0}' does not exists.".format(e))
djmail.exceptions.TemplateNotFound: Template 'emails/test_email1-subject.html' does not exists.
======================================================================
ERROR: test_simple_email_building (djmail.tests.TestTemplateEmailSending)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 79, in _render_message_subject
    subject = loader.render_to_string(template_name, context)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: emails/test_email1-subject.html
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/ad-m/djmail/djmail/tests.py", line 202, in test_simple_email_building
    context={'name': 'foo'})
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 173, in make_email
    return instance.make_email_object(to, context, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 90, in make_email_object
    subject = self._render_message_subject(context)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 81, in _render_message_subject
    raise exc.TemplateNotFound("Template '{0}' does not exists.".format(e))
djmail.exceptions.TemplateNotFound: Template 'emails/test_email1-subject.html' does not exists.
======================================================================
ERROR: test_simple_send_email_1 (djmail.tests.TestTemplateEmailSending)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 79, in _render_message_subject
    subject = loader.render_to_string(template_name, context)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: emails/test_email1-subject.html
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/test/utils.py", line 208, in inner
    return func(*args, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/tests.py", line 138, in test_simple_send_email_1
    email.send('to@example.com', {'name': 'foo'})
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 117, in send
    email = self.make_email_object(to, context, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 90, in make_email_object
    subject = self._render_message_subject(context)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 81, in _render_message_subject
    raise exc.TemplateNotFound("Template '{0}' does not exists.".format(e))
djmail.exceptions.TemplateNotFound: Template 'emails/test_email1-subject.html' does not exists.
======================================================================
ERROR: test_simple_send_email_2 (djmail.tests.TestTemplateEmailSending)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 79, in _render_message_subject
    subject = loader.render_to_string(template_name, context)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: emails/test_email2-subject.html
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/test/utils.py", line 208, in inner
    return func(*args, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/tests.py", line 155, in test_simple_send_email_2
    email.send('to@example.com', {'name': 'foo'})
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 117, in send
    email = self.make_email_object(to, context, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 90, in make_email_object
    subject = self._render_message_subject(context)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 81, in _render_message_subject
    raise exc.TemplateNotFound("Template '{0}' does not exists.".format(e))
djmail.exceptions.TemplateNotFound: Template 'emails/test_email2-subject.html' does not exists.
======================================================================
ERROR: test_simple_send_email_with_magic_builder_1 (djmail.tests.TestTemplateEmailSending)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 79, in _render_message_subject
    subject = loader.render_to_string(template_name, context)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: emails/test_email2-subject.html
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/test/utils.py", line 208, in inner
    return func(*args, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/tests.py", line 171, in test_simple_send_email_with_magic_builder_1
    email = mails.test_email2('to@example.com', {'name': 'foo'})
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 159, in _dynamic_email_generator
    email_instance = template_email.make_email_object(to, context, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 90, in make_email_object
    subject = self._render_message_subject(context)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 81, in _render_message_subject
    raise exc.TemplateNotFound("Template '{0}' does not exists.".format(e))
djmail.exceptions.TemplateNotFound: Template 'emails/test_email2-subject.html' does not exists.
======================================================================
ERROR: test_simple_send_email_with_magic_builder_1_with_extra_kwargs (djmail.tests.TestTemplateEmailSending)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 79, in _render_message_subject
    subject = loader.render_to_string(template_name, context)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: emails/test_email2-subject.html
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/test/utils.py", line 208, in inner
    return func(*args, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/tests.py", line 189, in test_simple_send_email_with_magic_builder_1_with_extra_kwargs
    from_email="no-reply@test.com")
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 159, in _dynamic_email_generator
    email_instance = template_email.make_email_object(to, context, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 90, in make_email_object
    subject = self._render_message_subject(context)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 81, in _render_message_subject
    raise exc.TemplateNotFound("Template '{0}' does not exists.".format(e))
djmail.exceptions.TemplateNotFound: Template 'emails/test_email2-subject.html' does not exists.
======================================================================
ERROR: test_simple_send_email_with_magic_builder_1_with_low_priority (djmail.tests.TestTemplateEmailSending)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 79, in _render_message_subject
    subject = loader.render_to_string(template_name, context)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: emails/test_email2-subject.html
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/test/utils.py", line 208, in inner
    return func(*args, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/tests.py", line 236, in test_simple_send_email_with_magic_builder_1_with_low_priority
    email = mails.test_email2('to@example.com', {'name': 'foo'}, priority=10)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 159, in _dynamic_email_generator
    email_instance = template_email.make_email_object(to, context, **kwargs)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 90, in make_email_object
    subject = self._render_message_subject(context)
  File "/home/travis/build/ad-m/djmail/djmail/template_mail.py", line 81, in _render_message_subject
    raise exc.TemplateNotFound("Template '{0}' does not exists.".format(e))
djmail.exceptions.TemplateNotFound: Template 'emails/test_email2-subject.html' does not exists.
----------------------------------------------------------------------
```

**Comment by ad-m** [comment]
Tests for django 1.9 provide warning:
```
../home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
```

**Comment by masci** [comment]
Guess this can be closed now?
